name: Android CI

on:
  push:
#    branches:
#      - main
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name in format = "2.0.4"'
        required: true
#      flavourName:
#        description: 'Flavour Name in format = "Dev/Production/Uat" etc'
#        required: true
      flavourName:
        type: choice
        description: 'Chose the Flavour'
        options:
          - staging
          - Production
          - Dr
          - Uat
          - UatEmulator
          - UatActual
          - UatPcloudy
          - Dev
          - DevEmulator
          - DevActual
          - DevPcloudy
        required: true
      buildType:
        type: choice
        description: 'Build Type'
        options:
          - Debug
          - Release
        required: true

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Build APK
        run: ./gradlew assemble${{ github.event.inputs.flavourName }}${{github.event.inputs.buildType}} --stacktrace
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
            # override default build-tools version (29.0.3) -- optional
            BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/release