name: Android CI

on:
  push:
#    branches:
#      - main
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name in format = "2.0.4"'
        required: true
      buildCommandName:
        description: 'Flavour Name in format = "assembleDevDebug/assembleProductionRelease" etc'
        required: true

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Build APK
        run: ./gradlew ${{github.event.inputs.buildCommandName}} --stacktrace
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
            # override default build-tools version (29.0.3) -- optional
            BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/release