name: Android CI

on:
  workflow_dispatch:
    inputs:
      flavourName:
        type: choice
        description: 'Chose the Flavour'
        options:
          - staging
          - production
          - dr
          - uat
          - uatEmulator
          - uatActual
          - uatPcloudy
          - dev
          - devEmulator
          - devActual
          - devPcloudy
        required: true
      buildType:
        type: choice
        description: 'Build Type'
        options:
          - debug
          - release
        required: true

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branchName }}
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
#      - name: Build
#        run: ./gradlew build --no-daemon
      - name: Build APK
        run: ./gradlew assemble${{ github.event.inputs.flavourName }}${{github.event.inputs.buildType}} --stacktrace
      - name: Form Output Directory
        uses: ASzc/change-string-case-action@v2
        env:
          BUILD_DIR: ${{ github.event.inputs.flavourName.lowercase }}/${{github.event.inputs.buildType.lowercase}}
        run:
          echo "BUILD_DIR="${COMMIT_VAR} >> $GITHUB_ENV
          echo "BUILD_DIR set to ${BUILD_DIR}"
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/${{ github.event.inputs.flavourName }}/${{github.event.inputs.buildType}}
#          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
            # override default build-tools version (29.0.3) -- optional
            BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/release